tenstorrent/tt-forge-models

tools/utils.py, yolov3/pytorch/loader.py
Move get_file helper/util function from tt-torch to tt-forge-models and use to load files
Tested change on tt-torch for yolov3 and it loaded the image and passed the test
=> Moving get_file into tt-forge-models

tools/utils.py
This is for https://github.com/tenstorrent/tt-torch/issues/796 and is inspired by the logic in https://github.com/tenstorrent/tt-torch/blob/main/tests/models/yolov10/test_yolov10.py#L25 for downloading images if not in cache.
The single api `get_file()` can now take a file path or url. 
- In case of file path, will fetch from cache that mirrors S3 bucket.
- In case of URL (detected by http, https), will fetch from web directly if doesn't exist in cache, otherwise will get from cache
- Files fetched from url are uniqified by url w/ hash and included in filename to avoid collisions with same filenames
Example outputs when updating yolov10 test in tt-torch to use this change (logic reduced to one line!) follows...
```
diff --git a/tests/models/yolov10/test_yolov10.py …
```
=> Update get_file() to take urls (download to cache or get from cache if exists)

centernet/pytorch/loader.py, yolov3/pytorch/loader.py, yolov4/pytorch/loader.py
- Simplifies weights download, and less reliance on s3 bucket/cache for letting external users run models
=> Use get_file(url) more for images and yolov3 custom weights

alexnet/__init__.py, alexnet/pytorch/__init__.py, alexnet/pytorch/loader.py, densenet/__init__.py, densenet/pytorch/__init__.py, densenet/pytorch/loader.py, ghostnet/__int__.py, ghostnet/pytorch/__init__.py, ghostnet/pytorch/loader.py, hrnet/__init__.py, hrnet/pytorch/__init__.py, hrnet/pytorch/loader.py, mgp_str_base/__init__.py, mgp_str_base/pytorch/__init__.py, mgp_str_base/pytorch/loader.py, mlp_mixer/__init__.py, mlp_mixer/pytorch/__init__.py, mlp_mixer/pytorch/loader.py, regnet/__init__.py, regnet/pytorch/__init__.py, regnet/pytorch/loader.py, resnext/__init__.py, resnext/pytorch/__init__.py, resnext/pytorch/loader.py, vgg/__int__.py, vgg/pytorch/__init__.py, vgg/pytorch/loader.py, xception/__init__.py, xception/pytorch/__init__.py, xception/pytorch/loader.py
This PR adds demos for below pytorch models(ported from tt-forge-fe)
- Alexnet
- Densenet
- Ghostnet
- HRNet
- MGP-STR
- MLP-Mixer
- Regnet
- Rexnext
- Vgg
- Xception
=> Add Pytorch model demos

centernet/pytorch/loader.py
**Problem description:**
This PR introduces the CenterNet model in ONNX format for multiple tasks, including **Object Detection** (OD), **Human Pose Estimation** (HPE), and **3D Bounding Box** (3D_BB).
The implementation is based on the official CenterNet [repository](https://github.com/xingyizhou/CenterNet) 
Supported model variants for each task are:
- Object Detection: dla1x, dla2x, resdcn101, resdcn18
- Human Pose Estimation: dla1x, dla3x
- 3D Bounding Box Detection: ddd_3dop, ddd_sub
=> Add ONNX Model Variants of CenterNet for OD, HPE, and 3D_BB

bloom/pytorch/loader.py, clip/pytorch/loader.py, codegen/pytorch/loader.py, deit/pytorch/loader.py
https://github.com/tenstorrent/tt-torch/issues/920
An alternative way to increase batch_size was suggested.
5 Models added in https://github.com/tenstorrent/tt-forge-models/pull/12 are updated to use the follow batch increase method (autoencoder_linear didn't require changes). 
self.test_input = "This is a sample text from "
inputs = self.tokenizer.encode_plus(
self.test_input,
return_tensors="pt",
max_length=32,
padding="max_length",
truncation=True,
)
inputs["input_ids"] = inputs["input_ids"].repeat_interleave(batch, dim=0)
inputs["attention_mask"] = inputs["attention_mask"].repeat_interleave(batch, dim=0)
This requires no changes to tt-torch tests.
=> Change batch_input generation

tools/utils.py
This PR fetches imagenet_class_index.json from url rather tha using the downloaded json from tt-forge-fe. This is required to use this function for demos which are being created in tt-forge repository
=> Fetch imagenet_class_index.json from url

mamba/pytorch/__init__.py, mamba/pytorch/loader.py, mgp_str_base/pytorch/loader.py, mnist/pytorch/loader.py, mnist/pytorch/src/utils.py, squeezebert/pytorch/loader.py, vilt/pytorch/loader.py, vit/pytorch/__init__.py, vit/pytorch/loader.py, xglm/pytorch/__init__.py, xglm/pytorch/loader.py, yolov3/pytorch/loader.py
https://github.com/tenstorrent/tt-torch/issues/920 
Some minor changes were needed in some models to ensure the tests in tt-torch can run.
- Added variants to mamba, vit and xglm models. Set the default variant to whatever was used initially to avoid creating an errors in tests that already use these models.
- Added `batch_size` as an optional parameter for `load_inputs()` of mamba, map_str_base, mnist, squeezebert, vilt, vit, xglm and yolov3
=> Update models for tt-torch tests

yolov3/pytorch/loader.py
#46 
Weights file for yolov3 fetched from URL, not accessible on CiV2
- Put weight in s3 bucket and use path from s3 bucket mirror instead of URL
=> Update yolov3 for yolov3_coco_01.h5 in s3 bucket

albert/masked_lm/pytorch/loader.py, hardnet/pytorch/loader.py, vovnet/pytorch/loader.py, yolox/pytorch/loader.py, yolox/pytorch/src/utils.py
This PR includes changes in model loaders of few models to get better demo performance.
- Correct image is used for hardnet model. 
- Random tensor inputs was replaced with actual image for vovnet model
- Weight file is being loaded using get_file for yolox model and cleaned up at end of demo.
- Post-processing steps are added for yolox model
=> Refactor model loading for better demo performance

bart/__init__.py, bart/pytorch/__init__.py, bart/pytorch/loader.py, config.py, deit/pytorch/loader.py, densenet/pytorch/loader.py, dla/pytorch/loader.py, efficientnet/pytorch/loader.py, googlenet/__init__.py, googlenet/pytorch/__init__.py, googlenet/pytorch/loader.py, hrnet/pytorch/loader.py, inception/__init__.py, inception/pytorch/__init__.py, inception/pytorch/loader.py, mlp_mixer/pytorch/loader.py, regnet/pytorch/loader.py, resnext/pytorch/loader.py, segformer/pytorch/loader.py, tools/utils.py, vgg/pytorch/loader.py, xception/pytorch/loader.py
- https://github.com/tenstorrent/tt-forge-fe/issues/2652
- Add variant support for existing models and bring up tt-forge-fe models in tt-forge-models.
- Added support for Inception,Bart and GoogleNet models from scratch.
- Added variant support for the following models:  
-  deit
-  densenet
-  dla
-  ghostnet
-  efficientnet
-  hrnet
-  mlp_mixer
-  regnet
-  resnext
-  segformer
-   Vgg
-   xception
- Test scripts and corresponding logs are attached. [set1_check.zip](https://github.com/user-attachments/files/21414087/set1_check.zip)
=> Bringup tt-forge-fe pytorch models - set1

yolov10/pytorch/loader.py
Currently, `yolo` models retrieve input image from an url. To make it more robust, huggingface `datasets` package can be used. If this change is accepted, the same will be changed for remaining yolo models
* `load_inputs()` is modified to use the datasets library to load an input image
* `cppe-5` dataset is used from datasets package
* removed import statements of cv2, numpy and get_file as they are not used now
Tested these changes in tt-xla repo and attached the logs below
[yolov10data.log](https://github.com/user-attachments/files/21366851/yolov10data.log)
[Shape of the image before and after the change](https://github.com/user-attachments/files/21371773/shape_yolo.log)
=> update yolov10 load_input function to load dataset

deit/pytorch/loader.py
https://github.com/tenstorrent/tt-forge-fe/issues/2695
Deit model faced below error in tt-forge-fe due to the absence of optional dtype conversion of input in deit
```
RuntimeError: TT_ASSERT @ /proj_sw/user_dev/kkannan/jul29_bgd25/tt-forge-fe/forge/csrc/passes/dataformat.cpp:98: node->output_df() == default_df_override || node_is_int
E       info:
E       Non integer Input activations should have output_df same as dataformat override which is: Float16_b, but node output_df is: Float32
```
Added optional dtype conversion of input in deit
=> Add optional dtype conversion for input in deit model

yolos/pytorch/loader.py, yolov3/pytorch/loader.py, yolov4/pytorch/loader.py, yolov5/pytorch/loader.py, yolox/pytorch/loader.py
Similar to this [PR](https://github.com/tenstorrent/tt-forge-models/pull/48), where yolov10 load_inputs() is updated to use datasets package instead of url
HuggingFace datasets package can be used instead of getting images from url
* load_inputs() function is updated to use huggingface datasets library instead of url
* similar image to the previous image is fetched from the datasets
* In some places, where numpy array is expected for postprocessing, image from the dataset is retrieved in numpy format
tested some of the yolo models after these changes and logs are attached below
[yolov3.log](https://github.com/user-attachments/files/21487655/yolov3.log)
[yolov4.log](https://github.com/user-attachments/files/21487659/yolov4.log)
=> update yolo models load_input functions to use datasets

albert/masked_lm/jax/__init__.py, albert/masked_lm/jax/loader.py
Add Jax model of Albert to tt-forge-models
A Loader class is added to implement ModelLoader for Albert model
Tested this model in tt-xla repo with this changes
PFA logs for reference: 
[alb_v2_base.log](https://github.com/user-attachments/files/21590624/alb_v2_base.log)
=> Add Albert Jax model for Masked LM

bert/sentence_embedding_generation/pytorch/loader.py, centernet/onnx/loader.py, falcon/pytorch/loader.py, mamba/pytorch/loader.py, openpose/v2/pytorch/loader.py, phi1/sequence_classification/pytorch/loader.py, phi1/token_classification/pytorch/loader.py, retinanet/pytorch/loader.py, vgg/pytorch/loader.py, vit/pytorch/loader.py, wide_resnet/pytorch/loader.py
None
- Hit some errors running phi1, wide_resnet, bert, retinanet due to typos
- Some passing VGG variants were removed in https://github.com/tenstorrent/tt-forge-models/pull/55
- Bring 7 vgg variants back as per my request in that PR
- Fix invalid ModelTask in phi1 models, bert, retinanet, centernet
- Fix wide_resnet typo and fix vit, mamba, falcon docs
- Also, fix a model name that had a space in it (OpenPose V2)
=> Fix few model issues and bring back 7x passing vgg variants

autoencoder_linear/pytorch/loader.py
As stated in this [PR](https://github.com/tenstorrent/tt-xla/pull/847) removing the usage of Matplotlib and used PIL instead.
Postprocessing function of `Autoencoder` model uses `Matplotlib.pyplot` to save the image which is a larger library in size. In order to avoid using such a larger package, `PIL` is used to save the image
Tested these changes with the test in tt-xla repository. PFA log for reference
[autoencoder.log](https://github.com/user-attachments/files/21598991/autoencoder.log)
=> Update Autoencoder postprocess to use PIL

llama/causal_lm/pytorch/loader.py, llama/sequence_classification/pytorch/loader.py
Setting overriding the type of all the input keys like this:
if dtype_override is not None:
for key in inputs:
inputs[key] = inputs[key].to(dtype_override)
Causes an error in tt-torch tests since not all input keys can be set to `torch.bfloat16`. Since this is an error in the forward pass and not in the tt-torch model tester, this must be changed in order for the model to pass with `dtype_override=torch.bfloat16`.
E       RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but                         
got CPUBFloat16Type instead (while checking arguments for embedding)
Removed these lines to allow the llama models to pass in tt-torch without error.
=> Remove unnecessary llama dtype_override

qwen_3/embedding/pytorch/loader.py
[TT-Torch Issue #985](https://github.com/tenstorrent/tt-torch/issues/985)
Qwen3 was having a low PCC its (0.74).
The low PCC (0.74) seemed to be just for one of the intermediate outputs and not for the model overall. All the other intermediates had PCC ~0.98.
The intermediate PCCs are evaluated because use_cache wasn't set to false for the model when loading. Added use_cache = false as a model_kwargs to qwen3 pytorch loader for the correction. New output PCC is 0.984.
=> Added use_cache = false for qwen3 loader to fix PCC issue in tt-torch

config.py, deepseek/deepseek_coder/pytorch/loader.py, deepseek/deepseek_math/pytorch/loader.py, gpt2/pytorch/loader.py, gpt_neo/causal_lm/pytorch/__init__.py, llava/pytorch/loader.py, resnet/pytorch/src/utils.py, tools/utils.py, yolov10/pytorch/loader.py, yolov5/pytorch/loader.py, yolov5/pytorch/src/utils.py, yolov8/pytorch/loader.py, yolov9/pytorch/loader.py
- https://github.com/tenstorrent/tt-forge/issues/374
- Fixes https://github.com/tenstorrent/tt-forge-models/issues/94
- YOLOv5, YOLOv8, YOLOv9, and YOLOv10 are missing post-processing steps.
- YOLOv5 also has incorrect preprocessing steps.
- ResNet post-processing includes an unnecessary BFP16 conversion of inputs.
- Added the required post-processing steps for YOLOv5, YOLOv8, YOLOv9, and YOLOv10.
- Fixed YOLOv5 preprocessing.
- Removed the unnecessary BFP16 input conversion in ResNet post-processing.
- [set2_check.zip](https://github.com/user-attachments/files/21896993/set2_check.zip)
=> Add post processing steps for yolov5,v8,v9,v10 and fix minor bugs

bigbird/question_answering/jax/loader.py, distilbert/masked_lm/jax/__init__.py, distilbert/masked_lm/jax/loader.py, electra/causal_lm/jax/__init__.py, electra/causal_lm/jax/loader.py
https://github.com/tenstorrent/tt-xla/issues/1045
* Add JAX models for Electra and Distilbert 
* added attention_type to bigbird model 
PFA logs for reference: 
[distilbert.log](https://github.com/user-attachments/files/21854539/distilbert.log)
[elec_base_discrim.log](https://github.com/user-attachments/files/21854541/elec_base_discrim.log)
[elec_base_generator.log](https://github.com/user-attachments/files/21854542/elec_base_generator.log)
[elec_large_discrim.log](https://github.com/user-attachments/files/21854543/elec_large_discrim.log)
[elec_small_discrim.log](https://github.com/user-attachments/files/21854544/elec_small_discrim.log)
[bbird_base_attn.log](https://github.com/user-attachments/files/21885508/bbird_base_attn.log)
[bbird_large_attn.log](https://github.com/user-attachments/fi …
=> Add JAX models for Electra and distilbert

gpt2/causal_lm/jax/__init__.py, gpt2/causal_lm/jax/loader.py, gpt_j/causal_lm/jax/__init__.py, gpt_j/causal_lm/jax/loader.py
https://github.com/tenstorrent/tt-xla/issues/1049
Add JAX models for GPT-J and GPT-2
=> Add JAX models for GPT2 and GPT-J

longt5/text_classification/jax/__init__.py, longt5/text_classification/jax/loader.py, marian_mt/text_classification/jax/__init__.py, marian_mt/text_classification/jax/loader.py
https://github.com/tenstorrent/tt-xla/issues/1071
Add JAX models for MarianMT and LongT5
PFA logs for reference :
[lt5_large_local_cg_main.log](https://github.com/user-attachments/files/21918553/lt5_large_local_cg_main.log)
[lt5_xl_tglobal_cg_main.log](https://github.com/user-attachments/files/21918555/lt5_xl_tglobal_cg_main.log)
[marianMT.log](https://github.com/user-attachments/files/21918557/marianMT.log)
[t5_base_cg_main.log](https://github.com/user-attachments/files/21918558/t5_base_cg_main.log)
=> Add JAX models for MarianMT and LongT5

suryaocr/pytorch/loader.py, suryaocr/pytorch/src/utils.py
Fixes https://github.com/tenstorrent/tt-forge-fe/issues/2799
The existing Surya OCR test fails with a `KeyError: 'encoder'` when attempting to load the model. This was observed using surya-ocr==0.13.0 and torch==2.1.0, which was the setup initially used when the test was introduced.
The current setup on main was initially tested with surya-ocr version 0.13.0 and torch version 2.1.0 when this test was brought up.Tried running cpu inference of surya-ocr version 0.13.0 which was returning the same above error, hence upgraded the surya-ocr version to latest which was 0.15.4 and ran cpu inference for ocr text task which was successful. Hence this PR restructures the existing test to be compatible with the package update. Text Detection and Text Recognition(OCR) Tasks are added as two separate …
=> Update Surya OCR loader for latest package version compatibility

detr3d/pytorch/__init__.py, detr3d/pytorch/loader.py, detr3d/pytorch/src/bbox_coder.py, detr3d/pytorch/src/dataset.py, detr3d/pytorch/src/detr.py, detr3d/pytorch/src/detr3d_head.py, detr3d/pytorch/src/fpn.py, detr3d/pytorch/src/gridmask.py, detr3d/pytorch/src/resnet.py, detr3d/pytorch/src/transformer.py
[1142](https://github.com/tenstorrent/tt-xla/issues/1142)
- Added the PyTorch implementation of the DETR3D model.
- The original implementation relied on external libraries such as mmcv, mmdet, and mmdet3d.
- Removed these dependencies by refactoring key functions, including config, DictAction, build_model, load_checkpoint, and set_random_seed.
- Substituted mmcv.load_checkpoint with model.load_state_dict() for loading model weights.
- Replaced dcnv2(modulated_conv_forward) (which relies on MMCV) with torchvision.ops.deform_conv2d to eliminate the MMCV dependency.
- One new ModelLoader class has been added to the respective directories.
=> Bring up Detr3d pytorch model

uniad/pytorch/__init__.py, uniad/pytorch/loader.py, uniad/pytorch/src/motion_head.py, uniad/pytorch/src/motion_utils.py, uniad/pytorch/src/occ_head.py, uniad/pytorch/src/occ_utils.py, uniad/pytorch/src/panseg_head.py, uniad/pytorch/src/panseg_utils.py, uniad/pytorch/src/planning_head.py, uniad/pytorch/src/planning_utils.py, uniad/pytorch/src/track_head.py, uniad/pytorch/src/track_utils.py, uniad/pytorch/src/transformer.py, uniad/pytorch/src/uniad_e2e.py, uniad/pytorch/src/uniad_track.py, uniad/pytorch/src/utils.py
https://github.com/tenstorrent/tt-xla/issues/1151
- Added the PyTorch implementation of the UNIAD model.
- The original implementation relied on external libraries such as mmcv, mmdet, and mmdet3d.
- Removed these dependencies by refactoring key functions, including config, DictAction, build_model, load_checkpoint, and set_random_seed.
- Replaced the use of build_dataset by directly passing randomly generated input tensors based on the shape and distribution of the NuScenes dataset.
- Substituted mmcv.load_checkpoint with model.load_state_dict() for loading model weights.
ModelLoader class for UNIAD has been added to the respective directories.
=> UNIAD Pytorch Model Bringup

maptr/pytorch/loader.py, maptr/pytorch/src/maptr.py
- Fixes https://github.com/tenstorrent/tt-xla/issues/1144
Add support for below target variants 
- [maptr_tiny_fusion_24e](https://github.com/hustvl/MapTR/blob/main/projects/configs/maptr/maptr_tiny_fusion_24e.py)
- [maptr_tiny_r50_av2_24e](https://github.com/hustvl/MapTR/blob/main/projects/configs/maptr/maptr_tiny_r50_av2_24e.py)
Added support for above variants
- Implemented [get_indice_pairs_3d](https://github.com/hustvl/MapTR/blob/a6872d8d9670bde17b4b01560f1221f88b443d55/mmdetection3d/mmdet3d/ops/spconv/ops.py#L87C53-L87C72), [indice_conv_fp32](https://github.com/hustvl/MapTR/blob/a6872d8d9670bde17b4b01560f1221f88b443d55/mmdetection3d/mmdet3d/ops/spconv/ops.py#L132C32-L132C48) in python (ported from C++).
- Validated results against the original CPU implementation using real inputs.
- …
=> Bringup MapTR's fusion & tiny_r50_av2_24e variant in pytorch

uniad/pytorch/src/planning_head.py, uniad/pytorch/src/uniad_e2e.py, uniad/pytorch/src/uniad_track.py
[tt-xla PR](https://github.com/tenstorrent/tt-xla/pull/1432)
While testing in tt-xla with the [UNIAD PR](https://github.com/tenstorrent/tt-forge-models/pull/155) changes the model is failed with error - torch._dynamo.exc.TorchRuntimeError: Dynamo failed to run FX node with fake tensors
I have debugged and fixed the issue in this PR. After applying this fix, in the tt-xla I got "Out of Memory: Not enough space to allocate 285081600 B L1 buffer across 64 banks, where each bank needs to store 4454400 B, but bank size is only 1366560 B"
=> UNIAD Fix for tt-xla TorchRuntimeError
